[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_fall_transfer_hook = "EPNDJXpqR9monFV27A2DuE6iSHJiQL1tySBr64XrCxHN"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
